version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: teste
    volumes:
      - ./databases/mongodb/data:/data/db
    ports:
      - 27017:27017
    networks:
      - bridge-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: teste
      ME_CONFIG_MONGODB_URL: mongodb://root:teste@mongo:27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    depends_on:
      - mongo
    networks:
      - bridge-network
networks:
  bridge-network:
    driver: "bridge"
    name: bridge-network
